on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Web Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.0p0c.com
        username: public_html_ftp@0p0c.com
        password: ${{ secrets.FTP_KEY }}
        log-level: verbose
        server-dir: 0p0c.com/